# Generated by Django 3.2.9 on 2021-11-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_alter_review_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImageClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.FileField(upload_to='')),
                ('content', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyVideoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.FileField(upload_to='')),
                ('content', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
