# Generated by Django 3.2.9 on 2021-11-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_auto_20211106_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idnumber',
            name='number',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
